# This workflow will install Python dependencies, run tests and upload the coverage for a series of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
    # Sets up a Python environments for use in actions
    - name: Set up Python ${{ matrix.python-versions }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-versions }}

    # Install dependencies
    - name: Install pip, tox and coverage
      run: |
        python -m pip install --upgrade pip
        pip install tox coverage
    # Python tests
    - name: Run Python tests
      run: make all-tests

    # Upload coverage (for public repos)
    - name: Upload the coverage to Codecov
      # Link for reference: https://github.com/codecov/codecov-action
      uses: codecov/codecov-action@v3
      with:
        flags: all-tests
        name: coverage
        fail_ci_if_error: true